### ISSUE TITLE
Implementation of pokerstove functionality

### ISSUE THREAD

**Issue by matthewha** [andrewprock/pokerstove#17]
Hi Andrew,

Thanks so much for open sourcing this library. I'm having a little difficulty in implementing pokerstove functionality. I'm trying to create a managed class that interfaces with the peval library. Anyway, it looks to me like that the evaluateShowdown function implements the pokerstove functionality. However, when passing a simple cardset to the function such as p1: AdKd p2: AcAs board: 6sJc5h, the winshare for p2 is "1" with all other returned equityresult variables as "0". When passing the same cardset for both players, the tieshares are 0.5.

Do you have a rough dot point guide on implementing the pokerstove functionality? It would be great if you could create a simple example similar to ps-eval which takes a number of hands and the board and returns equity results.

Thanks for any help.

Cheers,

Matt

**Comment by flocks** [comment]
Hey @matthewha I'm interested also in implementing the pokerstove functionnality for computing equities. Did you eventually manage to do it ?

**Comment by andrewprock** [comment]
unclear what the issue is here. Twodimes verifies that this is currently working

http://twodimes.net/h/?z=13210238
pokenum  -h ad kd  - ac as  -- 6s jc 5h 
Holdem Hi: 990 enumerated boards containing 6s Jc 5h
cards  win   %win  lose  %lose  tie  %tie     EV
Ad Kd   19   1.92   971  98.08    0  0.00  0.019
As Ac  971  98.08    19   1.92    0  0.00  0.981
