### ISSUE TITLE
ps-eval freezes with large ranges and no "--board" parameter

### ISSUE THREAD

**Issue by tiltmine** [andrewprock/pokerstove#38]
**Running the following command hangs for me:**

ps-eval 7s7d asqs,acqc,adqd,ahqh,asjs,acjc,adjd,ahjh,asts,actc,adtd,ahth,as9s,ac9c,ad9d,ah9h,as8s,ad8d,ah8h,as5s,ac5c,ad5d,ah5h,as4s,ac4c,ad4d,ah4h,ksqs,kcqc,kdqd,khqh,ksjs,kcjc,kdjd,khjh,ksts,kctc,kdtd,khth,ks9s,kc9c,kd9d,kh9h,qsjs,qcjc,qdjd,qhjh,qsts,qctc,qdtd,qhth,qs9s,qc9c,qd9d,qh9h,asqc,asqd,asqh,acqs,acqd,acqh,adqs,adqc,adqh,ahqs,ahqc,ahqd,ksqc,ksqd,ksqh,kcqs,kcqd,kcqh,kdqs,kdqc,kdqh,khqs,khqc,khqd,asjc,asjd,asjh,acjs,acjd,acjh,adjs,adjc,adjh,ahjs,ahjc,ahjd,jsts,jctc,jdtd,jhth,js9s,jc9c,jd9d,jh9h,ts9s,tc9c,td9d,th9h,ts8s,td8d,th8h,2s2c,2s2d,2s2h,2c2d,2c2h,2d2h,3s3c,3s3d,3s3h,3c3d,3c3h,3d3h,4s4c,4s4d,4s4h,4c4d,4c4h,4d4h,5s5c,5s5d,5s5h,5c5d,5c5h,5d5h,6s6c,6s6d,6s6h,6c6d,6c6h,6d6h,7s7d,7s7h,7d7h,8s8d,8s8h,8d8h,9s9c,9s9d,9s9h,9c9d,9c9h,9d9h,6s5s,6c5c,6d5d,6h5h,7s6s,7d6d,7h6h,8s7s,8d7d,8h7h,9s8s,9d8d,9h8h,9s7s,9d7d,9h7h

**However, when I run the same exact ranges in the GUI (leaving out the board), results come back instantly:**

Hand 0: 	57.789%  	57.43% 	00.36% 	     152421544 	   955711.50   { 7d7s }
Hand 1: 	42.211%  	41.85% 	00.36% 	     111074373 	   955711.50   { 99, 8d8h, 8d8s, 8h8s, 7d7h, 7d7s, 7h7s, 66-22, AQs-A9s, Ad8d, Ah8h, As8s, A5s-A4s, K9s+, Q9s+, J9s+, T9s, Td8d, Th8h, Ts8s, 9d8d, 9h8h, 9s8s, 9d7d, 9h7h, 9s7s, 8d7d, 8h7h, 8s7s, 7d6d, 7h6h, 7s6s, 65s, AQo-AJo, KQo }

**Also, I notice that when I add "--board AcKh3s" to the ps-eval command above it returns instantly.**

**Comment by apometta** [comment]
As of November 2018, the program no longer hangs.  It does, however, take an unusually long time - longer than it should even accounting for the time saving from specifying a board.  I thought it might be because you specified the 7s to be in both the second range and the first range, but even removing every hand from the second range containing a 7, in addition to other hands to trim the size, still results in a long calculation that the GUI can return instantly.

**Comment by andrewprock** [comment]
This is by design.
