### ISSUE TITLE
Looks like ps-eval improperly divides the number of ties

### ISSUE THREAD

**Issue by ydm** [andrewprock/pokerstove#45]
I've noticed something strange:

$ ./ps-eval -hacas -hkhkd
The hand acas has 81.2555 % equity (1388072 3269 0 0)
The hand khkd has 18.7445 % equity (317694 3269 0 0)

The actual number of ties is 6538, but ps-eval reports it to be just half of that -- 3269.

Is this a bug or it's intended to work this way. If it's the later, shouldn't the "tie" number be renamed to something less misleading?

**Comment by apometta** [comment]
It must be intended, since the GUI Windows program reports the exact same outcome.  What I find interesting is this:

```bash
$ ./ps-eval -h AcAs -h KcKs
The hand AcAs has 82.6366 % equity (1410336 4654 0 0)
The hand KcKs has 17.3634 % equity (292660 4654 0 0)
```

Which is counting 4,654 ties.  The GUI Windows version (running on Wine) shows 4,664 ties apiece in this same instance.  It gets the number of wins for each hand correct - I believe it might simply be a small counting error in the matter of counting ties.  It might even just be a printing error.

**Comment by andrewprock** [comment]
It's counting the number of shares due to ties, not the number of ties.
